export const HEADER = {
  DASHBOARD_DESKTOP_HEIGHT: 64,
};

export const NAVBAR = {
  DASHBOARD_WIDTH: 280,
  DASHBOARD_ITEM_ROOT_HEIGHT: 48,
  DASHBOARD_ITEM_SUB_HEIGHT: 40,
};

export const ICON = {
  NAVBAR_ITEM: 24,
  NAVBAR_ITEM_HORIZONTAL: 24,
};
